apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: counter-app
  description: Counter Application for managing counters
spec:
  owner: group:team-a
  domain: counting
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: counting
  description: Everything about counting
spec:
  owner: group:team-a
