apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter-service
  description: A simple counter service
  tags:
    - kotlin
  annotations:
    github.com/project-slug: 'harshadnawathe/counter'
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: app-services
