apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter-service
  description: A simple counter service
  tags:
    - kotlin
spec:
  type: app
  lifecycle: experimental
  owner: harshad
  system: app-services
