apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter-service
  description: A simple counter service
  tags:
    - kotlin
  annotations:
    github.com/project-slug: 'harshadnawathe/counter'
    jacoco/reports/csv: 'jacoco-reports-csv'
  links:
    - url: https://github.com/harshadnawathe/counter/blob/master/README.md
      title: Counter Service
spec:
  type: service
  lifecycle: experimental
  owner: group:team-a
  system: counter-app
  providesApis: 
    - api:counter-api
